#!/bin/bash

# This script is for running desc2matrix on the descriptions
# that were subsetting to only include those within the Solanum Key: https://app.xper3.fr/xper3GeneratedFiles/publish/identification/-3915026624309343770/mkey.html

# Go to main branch directory
cd ../../..
# Activate venv
# source ../env/Scripts/activate
# Run desc2matrix_accum scripts
python scripts/desc2matrix/desc2matrix_accum.py data/solanaceae-desc-subset.txt script_output/desc2matrix/wcharlist/subset/accum_subset_2nd.json --desctype=general --numctx=8192 --numpredict=4096
python scripts/desc2matrix/desc2matrix_accum_tab.py data/solanaceae-desc-subset.txt script_output/desc2matrix/wcharlist/subset/accum_tab_subset_2nd.json --desctype=general --numctx=8192 --numpredict=4096
python scripts/desc2matrix/desc2matrix_accum_followup.py data/solanaceae-desc-subset.txt script_output/desc2matrix/wcharlist/subset/accum_f_subset_2nd.json --desctype=general --numpredict=4096
python scripts/desc2matrix/desc2matrix_accum_tf.py data/solanaceae-desc-subset.txt script_output/desc2matrix/wcharlist/subset/accum_tf_subset_2nd.json --desctype=general --numpredict=4096
# Run desc2matrix_wcharlist scripts
python scripts/desc2matrix/desc2matrix_wcharlist.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist.txt script_output/desc2matrix/wcharlist/subset/wcharlist_subset_2nd.json --desctype=general --charlistsep="; " --numctx=8192 --numpredict=4096
python scripts/desc2matrix/desc2matrix_wcharlist_followup.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist.txt script_output/desc2matrix/wcharlist/subset/wcharlist_f_subset_2nd.json --desctype=general --charlistsep="; " --numpredict=4096
# Test desc2matrix_wcharlist scripts using charlists generated by trait accumulation
python scripts/desc2matrix/desc2matrix_wcharlist.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist_gen_shorter.txt script_output/desc2matrix/wcharlist/subset/wcharlist_sgenlist_subset_2nd.json --desctype=general --charlistsep="; " --numctx=8192 --numpredict=4096
python scripts/desc2matrix/desc2matrix_wcharlist_followup.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist_gen_shorter.txt script_output/desc2matrix/wcharlist/subset/wcharlist_f_sgenlist_subset_2nd.json --desctype=general --charlistsep="; " --numpredict=4096
python scripts/desc2matrix/desc2matrix_wcharlist.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist_gen_longer.txt script_output/desc2matrix/wcharlist/subset/wcharlist_lgenlist_subset_2nd.json --desctype=general --charlistsep="; " --numctx=8192 --numpredict=4096
python scripts/desc2matrix/desc2matrix_wcharlist_followup.py data/solanaceae-desc-subset.txt scripts/desc2matrix/charlists/solanum_charlist_gen_longer.txt script_output/desc2matrix/wcharlist/subset/wcharlist_f_lgenlist_subset_2nd.json --desctype=general --charlistsep="; " --numpredict=4096
# Deactivate venv
# deactivate